# https://circleci.com/docs/2.0/language-javascript

version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout

      # Download and cache dependencies. Use the latest cache
      # if no exact match is found.
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "package.json" }}
            - v1-node-dependencies-

      - run:
          name: Installing dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-node-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building the site
          command: yarn build

      - run:
          name: Compressing output
          command: find dist/ -type f -exec gzip -9 "{}" \; -exec mv "{}.gz" "{}" \;

      - aws-s3/sync:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist/
          to: "s3://nikhil.io/"
          arguments: |
            --delete \
            --cache-control max-age=315360000 \
            --content-encoding gzip

      - run:
          name: Invalidating CloudFront distribution
          command: |
            aws cloudfront create-invalidation \
              --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
              --paths '/index.html'
